In [2]:
# opencv is used to work with images

# opencv is a third party library > pypi.org


SyntaxError: invalid syntax. Perhaps you forgot a comma? (4198322606.py, line 4)

In [1]:
pip install opencv-contrib-python


   ---------------------------------------- 0.0/45.3 MB ? eta -:--:--
   ---------------------------------------- 0.2/45.3 MB 5.0 MB/s eta 0:00:10
   ---------------------------------------- 0.4/45.3 MB 3.8 MB/s eta 0:00:12
    --------------------------------------- 0.6/45.3 MB 4.3 MB/s eta 0:00:11
    --------------------------------------- 0.8/45.3 MB 4.0 MB/s eta 0:00:12
    --------------------------------------- 1.0/45.3 MB 4.2 MB/s eta 0:00:11
   - -------------------------------------- 1.3/45.3 MB 4.5 MB/s eta 0:00:10
   - -------------------------------------- 1.4/45.3 MB 4.5 MB/s eta 0:00:10
   - -------------------------------------- 1.6/45.3 MB 4.3 MB/s eta 0:00:11
   - -------------------------------------- 1.9/45.3 MB 4.4 MB/s eta 0:00:10
   - -------------------------------------- 2.1/45.3 MB 4.4 MB/s eta 0:00:10
   - -------------------------------------- 2.3/45.3 MB 4.5 MB/s eta 0:00:10
   -- ------------------------------------- 2.5/45.3 MB 4.6 MB/s eta 0:00:10
   -- 

In [4]:
import cv2

In [8]:
img=cv2.imread(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\computervision\kate.jpg")
cv2.imshow("window1",img)
cv2.waitKey(10000)        # 1000 milli second =1 sec
cv2.destroyWindow("window1")

In [7]:
img=cv2.imread(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\computervision\kate.jpg")
# cv2.imshow("window1",img)
# cv2.waitKey(10000)        # 1000 milli second =1 sec
# cv2.destroyWindow("window1")
print(img)

[[[224 231 234]
  [224 231 234]
  [224 231 234]
  ...
  [181 199 200]
  [182 197 199]
  [182 197 199]]

 [[224 231 234]
  [224 231 234]
  [224 231 234]
  ...
  [181 199 200]
  [183 198 200]
  [182 197 199]]

 [[224 231 234]
  [224 231 234]
  [224 231 234]
  ...
  [184 199 201]
  [183 198 200]
  [183 198 200]]

 ...

 [[ 12  12  12]
  [ 12  12  12]
  [ 12  12  12]
  ...
  [  9   9   9]
  [ 10  10  10]
  [ 12  12  12]]

 [[ 12  12  12]
  [ 12  12  12]
  [ 12  12  12]
  ...
  [  9   9   9]
  [ 10  10  10]
  [ 12  12  12]]

 [[ 12  12  12]
  [ 12  12  12]
  [ 13  13  13]
  ...
  [  9   9   9]
  [ 10  10  10]
  [ 12  12  12]]]


In [ ]:
ANSI:

Ascii character set : 128 character

In [9]:
bin(127)

'0b1111111'

In [1]:
import cv2

In [4]:
img=cv2.imread(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\computervision\kate.jpg")
cv2.imshow("window1",img)
cv2.waitKey(10000)        # 1000 milli second =1 sec
cv2.destroyWindow("window1")

In [2]:
import cv2
img=cv2.imread(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\computervision\kate.jpg")
cv2.imshow("window1",img)
cv2.waitKey(10000)        # 1000 milli second =1 sec
cv2.destroyWindow("window1")

In [6]:

img=cv2.imread(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\computervision\kate.jpg")
cv2.imshow("window1",img)
cv2.waitKey(10000)        # 1000 milli second =1 sec
cv2.destroyWindow("window1")

In [8]:
print(img)
print(img.ndim)

[[[224 231 234]
  [224 231 234]
  [224 231 234]
  ...
  [181 199 200]
  [182 197 199]
  [182 197 199]]

 [[224 231 234]
  [224 231 234]
  [224 231 234]
  ...
  [181 199 200]
  [183 198 200]
  [182 197 199]]

 [[224 231 234]
  [224 231 234]
  [224 231 234]
  ...
  [184 199 201]
  [183 198 200]
  [183 198 200]]

 ...

 [[ 12  12  12]
  [ 12  12  12]
  [ 12  12  12]
  ...
  [  9   9   9]
  [ 10  10  10]
  [ 12  12  12]]

 [[ 12  12  12]
  [ 12  12  12]
  [ 12  12  12]
  ...
  [  9   9   9]
  [ 10  10  10]
  [ 12  12  12]]

 [[ 12  12  12]
  [ 12  12  12]
  [ 13  13  13]
  ...
  [  9   9   9]
  [ 10  10  10]
  [ 12  12  12]]]
3


In [2]:
import cv2
import numpy as np

In [3]:
img2=np.random.randint(0,256,(100,100,3))
cv2.imshow("window",img2)
cv2.waitKey()
cv2.destroyWindow("window")


error: OpenCV(4.9.0) D:/a/opencv-python/opencv-python/opencv/modules/highgui/src/precomp.hpp:155: error: (-215:Assertion failed) src_depth != CV_16F && src_depth != CV_32S in function 'convertToShow'


: 

In [4]:
import numpy as np
import cv2

# Generate a random image with uint8 data type
img2 = np.random.randint(0, 256, (100, 100, 3), dtype=np.uint8)

# Display the image
cv2.imshow("window", img2)
cv2.waitKey()
cv2.destroyAllWindows()


In [5]:

img=cv2.imread(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\computervision\sachine.webp")
cv2.imshow("window1",img)
cv2.waitKey(10000)        # 1000 milli second =1 sec
cv2.destroyWindow("window1")

In [6]:
img

array([[[103, 119, 125],
        [103, 119, 125],
        [103, 119, 125],
        ...,
        [100, 116, 124],
        [100, 116, 124],
        [100, 116, 124]],

       [[103, 119, 125],
        [103, 119, 125],
        [103, 119, 125],
        ...,
        [100, 116, 124],
        [100, 116, 124],
        [100, 116, 124]],

       [[103, 119, 125],
        [103, 119, 125],
        [103, 119, 125],
        ...,
        [100, 116, 124],
        [100, 116, 124],
        [100, 116, 124]],

       ...,

       [[200,  95,  28],
        [199,  94,  27],
        [208, 104,  35],
        ...,
        [110, 123, 133],
        [110, 123, 133],
        [110, 123, 133]],

       [[204,  98,  33],
        [204,  99,  32],
        [204, 100,  30],
        ...,
        [112, 124, 134],
        [112, 124, 134],
        [112, 124, 134]],

       [[204,  98,  33],
        [204,  98,  33],
        [204,  99,  32],
        ...,
        [112, 124, 134],
        [112, 124, 134],
        [112, 124, 134]]

In [ ]:
img.flatten  

In [8]:
img

160*206*3

98880

In [9]:
img

array([[[103, 119, 125],
        [103, 119, 125],
        [103, 119, 125],
        ...,
        [100, 116, 124],
        [100, 116, 124],
        [100, 116, 124]],

       [[103, 119, 125],
        [103, 119, 125],
        [103, 119, 125],
        ...,
        [100, 116, 124],
        [100, 116, 124],
        [100, 116, 124]],

       [[103, 119, 125],
        [103, 119, 125],
        [103, 119, 125],
        ...,
        [100, 116, 124],
        [100, 116, 124],
        [100, 116, 124]],

       ...,

       [[200,  95,  28],
        [199,  94,  27],
        [208, 104,  35],
        ...,
        [110, 123, 133],
        [110, 123, 133],
        [110, 123, 133]],

       [[204,  98,  33],
        [204,  99,  32],
        [204, 100,  30],
        ...,
        [112, 124, 134],
        [112, 124, 134],
        [112, 124, 134]],

       [[204,  98,  33],
        [204,  98,  33],
        [204,  99,  32],
        ...,
        [112, 124, 134],
        [112, 124, 134],
        [112, 124, 134]]

In [12]:
random_img=img.flatten()

In [13]:
np.random.shuffle(random_img)

In [14]:
random_img

array([  8, 107, 183, ..., 133, 105,  74], dtype=uint8)

In [15]:
random_img_reshape=np.reshape(random_img,(160,206,3))

In [16]:
random_img_reshape

array([[[  8, 107, 183],
        [ 74, 133, 125],
        [ 59, 121, 180],
        ...,
        [115, 203,  86],
        [ 70, 114,  94],
        [116,  90, 110]],

       [[ 57, 127, 108],
        [123, 131,  44],
        [135,  27,  34],
        ...,
        [ 98,  22,  90],
        [109,  61, 109],
        [173,  11,  13]],

       [[122,   9, 138],
        [235, 122, 205],
        [160, 207, 127],
        ...,
        [ 37, 135, 136],
        [105, 128, 120],
        [ 84, 107, 122]],

       ...,

       [[125, 135,  52],
        [ 87, 105, 113],
        [ 39, 125, 128],
        ...,
        [170, 114, 129],
        [110, 126,  18],
        [ 69, 136, 182]],

       [[ 17, 124, 103],
        [ 33, 118,  18],
        [ 64, 122, 123],
        ...,
        [  3, 107, 140],
        [131,  55, 179],
        [ 84, 193, 117]],

       [[ 11,  51, 129],
        [199, 106, 121],
        [102,   0, 121],
        ...,
        [ 51,  11, 127],
        [ 89, 103, 120],
        [133, 105,  74]]

In [17]:
cv2.imshow("window",random_img_reshape)
cv2.waitKey()
cv2.destroyWindow("window")

In [1]:
import cv2

In [6]:
img3=cv2.imread(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\computervision\sachine.webp")
cv2.imshow("window",img3)
cv2.waitKey()
cv2.destroyWindow("window")

In [7]:
img3=cv2.imread(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\computervision\sachine.webp")
cv2.imshow("window",img3-1)
cv2.waitKey()
cv2.destroyWindow("window")

In [9]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a-1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[0 1 2 3 4]


In [11]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a)
print(type(a))
print(a-1)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
[[0 1]
 [2 3]]


In [12]:
import numpy as np
a=np.array([[[1,2],[3,4]]])
print(a)
print(type(a))
print(a-1)

[[[1 2]
  [3 4]]]
<class 'numpy.ndarray'>
[[[0 1]
  [2 3]]]


In [17]:
img3=cv2.imread(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\computervision\sachine.webp")
cv2.imshow("original",img3)
cv2.imshow("duplicat1",img3-1)
cv2.imshow("duplicat2",img3-2)
cv2.waitKey()
cv2.destroyAllWindows()

In [19]:
# option1:  to read a colored image into black and white pixel
img3=cv2.imread(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\computervision\sachine.webp",0)
cv2.imshow("original",img3)
cv2.waitKey()
cv2.destroyAllWindows()

In [20]:
img3

array([[119, 119, 119, ..., 117, 117, 117],
       [119, 119, 119, ..., 117, 117, 117],
       [119, 119, 119, ..., 117, 117, 117],
       ...,
       [ 87,  86,  95, ..., 125, 125, 125],
       [ 91,  91,  91, ..., 126, 126, 126],
       [ 91,  91,  91, ..., 126, 126, 126]], dtype=uint8)

In [23]:
# option2:  to read a colored image into black and white pixel
img3=cv2.imread(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\computervision\sachine.webp")   # read color image
img4=cv2.cvtColor(img3,cv2.COLOR_BGR2GRAY)     # converting colored image into grey(black and white)
cv2.imshow("original",img4)
cv2.imshow("colored image",img3)
cv2.waitKey()
cv2.destroyAllWindows()

In [32]:
img3=cv2.imread(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\computervision\sachine.webp")   # read color image

blue,green,red=cv2.split(img3)
cv2.imshow("blue_window",blue)
cv2.imshow("green_window",green)
cv2.imshow("red_window",red)
cv2.waitKey()
cv2.destroyAllWindows()

In [28]:
blue

array([[103, 103, 103, ..., 100, 100, 100],
       [103, 103, 103, ..., 100, 100, 100],
       [103, 103, 103, ..., 100, 100, 100],
       ...,
       [200, 199, 208, ..., 110, 110, 110],
       [204, 204, 204, ..., 112, 112, 112],
       [204, 204, 204, ..., 112, 112, 112]], dtype=uint8)

In [29]:
green

array([[119, 119, 119, ..., 116, 116, 116],
       [119, 119, 119, ..., 116, 116, 116],
       [119, 119, 119, ..., 116, 116, 116],
       ...,
       [ 95,  94, 104, ..., 123, 123, 123],
       [ 98,  99, 100, ..., 124, 124, 124],
       [ 98,  98,  99, ..., 124, 124, 124]], dtype=uint8)

In [30]:
red

array([[125, 125, 125, ..., 124, 124, 124],
       [125, 125, 125, ..., 124, 124, 124],
       [125, 125, 125, ..., 124, 124, 124],
       ...,
       [ 28,  27,  35, ..., 133, 133, 133],
       [ 33,  32,  30, ..., 134, 134, 134],
       [ 33,  33,  32, ..., 134, 134, 134]], dtype=uint8)

In [34]:
img=cv2.merge((blue,green,red))
cv2.imshow("window", img)
cv2.waitKey()
cv2.destroyAllWindows()

In [35]:
img

array([[[103, 119, 125],
        [103, 119, 125],
        [103, 119, 125],
        ...,
        [100, 116, 124],
        [100, 116, 124],
        [100, 116, 124]],

       [[103, 119, 125],
        [103, 119, 125],
        [103, 119, 125],
        ...,
        [100, 116, 124],
        [100, 116, 124],
        [100, 116, 124]],

       [[103, 119, 125],
        [103, 119, 125],
        [103, 119, 125],
        ...,
        [100, 116, 124],
        [100, 116, 124],
        [100, 116, 124]],

       ...,

       [[200,  95,  28],
        [199,  94,  27],
        [208, 104,  35],
        ...,
        [110, 123, 133],
        [110, 123, 133],
        [110, 123, 133]],

       [[204,  98,  33],
        [204,  99,  32],
        [204, 100,  30],
        ...,
        [112, 124, 134],
        [112, 124, 134],
        [112, 124, 134]],

       [[204,  98,  33],
        [204,  98,  33],
        [204,  99,  32],
        ...,
        [112, 124, 134],
        [112, 124, 134],
        [112, 124, 134]]

In [1]:
# how to play with image: change brightness, constrast, and much more

In [3]:
import cv2

In [4]:
img=cv2.imread(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\computervision\sachine.webp")
cv2.imshow("win",img)
cv2.waitKey()
cv2.destroyAllWindows()

In [5]:
img=cv2.imread(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\computervision\sachine.webp",0)
cv2.imshow("win",img)
cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
img

array([[119, 119, 119, ..., 117, 117, 117],
       [119, 119, 119, ..., 117, 117, 117],
       [119, 119, 119, ..., 117, 117, 117],
       ...,
       [ 87,  86,  95, ..., 125, 125, 125],
       [ 91,  91,  91, ..., 126, 126, 126],
       [ 91,  91,  91, ..., 126, 126, 126]], dtype=uint8)

In [7]:
img=cv2.imread(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\computervision\sachine.webp")
img2=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imshow("win",img2)
cv2.waitKey()
cv2.destroyAllWindows()

In [11]:
img=cv2.imread(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\computervision\sachine.webp")
img2=cv2.convertScaleAbs(img,alpha=2, beta=50)      #aplha=1-3; beta 0-100
cv2.imshow("original",img)
cv2.imshow("win",img2)
cv2.waitKey()
cv2.destroyAllWindows()

In [16]:
img=cv2.imread(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\computervision\sachine.webp")
img2=cv2.convertScaleAbs(img,alpha=1)      #aplha=1-3; beta 0-100
cv2.imshow("original",img)
cv2.imshow("win",img2)
cv2.waitKey()
cv2.destroyAllWindows()

In [21]:
img=cv2.imread(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\computervision\sachine.webp")
img2=cv2.convertScaleAbs(img,beta=100)      #aplha=1-3; beta 0-100
cv2.imshow("original",img)
cv2.imshow("win",img2)
cv2.waitKey()
cv2.destroyAllWindows()

In [26]:
img=cv2.imread(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\computervision\kate.jpg")  
img2=cv2.resize(img,(160,206))   # kate original image size =1000*1535 px  convert it to 160*206 px  and stored it into a variable called "img2"
cv2.imwrite(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\computervision\resize_kate_image.jpg",img2)
cv2.imshow("win",img2)
cv2.waitKey()
cv2.destroyAllWindows()

In [37]:
# merge kate image and sachin image together

sachine=cv2.imread(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\computervision\sachine.webp")
kate=cv2.imread(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\computervision\resize_kate_image.jpg")

sachine_kate=cv2.addWeighted(sachine,0.9,kate,0.3,0)
cv2.imshow("window",sachine_kate)
cv2.waitKey()
cv2.destroyAllWindows()