In [2]:
# downloading data from kaggle house price prediction  

# https://www.kaggle.com/datasets/jacksondivakarr/house-price-prediction-dataset

In [3]:
import pandas as pd

In [98]:
df=pd.read_csv(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\scaling\csvdata.csv")

In [99]:
df

Unnamed: 0       City     Price  Area                         Location  \
0               0  Bangalore  30000000  3340                 JP Nagar Phase 1   
1               1  Bangalore   7888000  1045       Dasarahalli on Tumkur Road   
2               2  Bangalore   4866000  1179  Kannur on Thanisandra Main Road   
3               3  Bangalore   8358000  1675                     Doddanekundi   
4               4  Bangalore   6845000  1670                          Kengeri   
...           ...        ...       ...   ...                              ...   
29130        7714     Mumbai  14500000  1180                   Mira Road East   
29131        7715     Mumbai  14500000   530                     Naigaon East   
29132        7716     Mumbai   4100000   700                         Shirgaon   
29133        7717     Mumbai   2750000   995                   Mira Road East   
29134        7718     Mumbai   2750000  1020                   Mira Road East   

       No. of Bedrooms  
0                    4  
1                    2  
2                    2  
3                    3  
4                    3  
...                ...  
29130                2  
29131                1  
29132                1  
29133                2  
29134                2  

[29135 rows x 6 columns]

In [100]:

df.Location.value_counts()

Location
New Town              687
Kharghar              566
Thane West            503
Mira Road East        453
Rajarhat              403
                     ... 
Matrusri Nagar          1
Padma Colony            1
Happy Homes Colony      1
Old Nallakunta          1
Padle Gaon              1
Name: count, Length: 1776, dtype: int64

In [101]:
df1=df.iloc[:,[1,2,3,5]]

In [102]:
df1

City     Price  Area  No. of Bedrooms
0      Bangalore  30000000  3340                4
1      Bangalore   7888000  1045                2
2      Bangalore   4866000  1179                2
3      Bangalore   8358000  1675                3
4      Bangalore   6845000  1670                3
...          ...       ...   ...              ...
29130     Mumbai  14500000  1180                2
29131     Mumbai  14500000   530                1
29132     Mumbai   4100000   700                1
29133     Mumbai   2750000   995                2
29134     Mumbai   2750000  1020                2

[29135 rows x 4 columns]

In [103]:

df1.City.value_counts()

City
Mumbai       6925
Kolkata      6275
Bangalore    5521
Chennai      4307
Delhi        4109
Hyderabad    1998
Name: count, dtype: int64

In [104]:
df2=df1.iloc[:,[0,2,3,1]]
df2

City  Area  No. of Bedrooms     Price
0      Bangalore  3340                4  30000000
1      Bangalore  1045                2   7888000
2      Bangalore  1179                2   4866000
3      Bangalore  1675                3   8358000
4      Bangalore  1670                3   6845000
...          ...   ...              ...       ...
29130     Mumbai  1180                2  14500000
29131     Mumbai   530                1  14500000
29132     Mumbai   700                1   4100000
29133     Mumbai   995                2   2750000
29134     Mumbai  1020                2   2750000

[29135 rows x 4 columns]

In [105]:
# One hot encoding of city column using map()
df2.City=df2.City.map({"Mumbai":0,"Kolkata":1,"Bangalore":2,"Chennai":3,"Delhi":4,"Hyderabad":5})

In [106]:
df2

City  Area  No. of Bedrooms     Price
0         2  3340                4  30000000
1         2  1045                2   7888000
2         2  1179                2   4866000
3         2  1675                3   8358000
4         2  1670                3   6845000
...     ...   ...              ...       ...
29130     0  1180                2  14500000
29131     0   530                1  14500000
29132     0   700                1   4100000
29133     0   995                2   2750000
29134     0  1020                2   2750000

[29135 rows x 4 columns]

In [107]:
X=df2.iloc[:,:-1].values    #feature

In [108]:
X

array([[   2, 3340,    4],
       [   2, 1045,    2],
       [   2, 1179,    2],
       ...,
       [   0,  700,    1],
       [   0,  995,    2],
       [   0, 1020,    2]], dtype=int64)

In [109]:
y=df2.Price.values

In [110]:
y

array([30000000,  7888000,  4866000, ...,  4100000,  2750000,  2750000],
      dtype=int64)

In [111]:
# split data into two part which is called training and testing part
from sklearn.model_selection import train_test_split

In [112]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.70,random_state=42)

In [113]:
X_train.shape

(20394, 3)

In [114]:
X_test.shape

(8741, 3)

In [115]:
from sklearn.linear_model import LinearRegression

In [116]:
model=LinearRegression()

In [117]:
model.fit(X_train,y_train)

LinearRegression()

In [118]:
model.predict([[2,3340,4]])

array([29700990.95229086])

In [119]:
# calculating the accuracy of training dataset

# r2_score is use to calculate regression model's score only
from sklearn.metrics import r2_score

In [120]:
X_train_predict=model.predict(X_train)
X_train_predict

array([11424473.6220914 , 16533347.14731268, 12793108.65920952, ...,
       11772791.1825649 ,  8974183.45114234, 24284541.12246221])

In [121]:
r2_score(y_train,X_train_predict)
print("training score : ",r2_score(y_train,X_train_predict))

training score :  0.09411944325600408


In [122]:
# calculating testing data's score   X_test,y_test
X_test_predict=model.predict(X_test)
X_test_predict

array([ 8492844.0987548 , 15312768.86963791, 22080814.44220032, ...,
       14926505.84506652, 44707471.20432013, 10982774.29226347])

In [123]:
r2_score(y_test,X_test_predict)
print("Testing score:",r2_score(y_test,X_test_predict))

Testing score: 0.047683988915609765


In [124]:
# After scaling

In [125]:
X_train
y_train

array([ 5200000,  4300000, 25000000, ...,  7200000,  3900000,  2600000],
      dtype=int64)

In [126]:
# demo of scaling

In [127]:
import numpy as np

In [128]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [129]:
print(a)

[1 2 3 4 5 6 7 8 9]


In [130]:
a/9

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889, 1.        ])

In [131]:
model.coef_

array([ -695392.10925955,    10686.39568029, -2432941.10817136])

In [132]:
c=model.intercept_
c

5130978.031310959

In [133]:
x1,x2,x3=[2,3340,4]
print("x1",x1)
print("x2",x2)
print("x3",x3)

x1 2
x2 3340
x3 4


In [134]:
m1,m2,m3=[ -695392.10925955,    10686.39568029, -2432941.10817136]
print("m1",m1)
print("m2",m2)
print("m3",m3)

m1 -695392.10925955
m2 10686.39568029
m3 -2432941.10817136


In [135]:
m1*x1

-1390784.2185191

In [136]:
m2*x2

35692561.572168596

In [137]:
m3*x3

-9731764.43268544

In [138]:
from sklearn.preprocessing import MinMaxScaler


In [139]:
sc=MinMaxScaler()

In [140]:
X_scale=sc.fit_transform(X)
X_scale

array([[0.4       , 0.19873418, 0.375     ],
       [0.4       , 0.05348101, 0.125     ],
       [0.4       , 0.06196203, 0.125     ],
       ...,
       [0.        , 0.03164557, 0.        ],
       [0.        , 0.05031646, 0.125     ],
       [0.        , 0.05189873, 0.125     ]])

In [141]:
y

array([30000000,  7888000,  4866000, ...,  4100000,  2750000,  2750000],
      dtype=int64)

In [142]:
from sklearn.model_selection import train_test_split

In [143]:
X_train,X_test,y_train,y_test=train_test_split(X_scale,y,train_size=0.70,random_state=42)

In [144]:
X_train

array([[0.2       , 0.07196203, 0.25      ],
       [0.        , 0.09810127, 0.25      ],
       [0.        , 0.07594937, 0.25      ],
       ...,
       [0.4       , 0.06373418, 0.125     ],
       [1.        , 0.07392405, 0.25      ],
       [0.        , 0.15841772, 0.375     ]])

In [145]:
X_test

array([[0.2       , 0.04018987, 0.125     ],
       [0.6       , 0.10322785, 0.25      ],
       [0.6       , 0.15772152, 0.375     ],
       ...,
       [1.        , 0.10917722, 0.25      ],
       [0.6       , 0.30613924, 0.5       ],
       [0.2       , 0.05493671, 0.125     ]])

In [147]:
model2=LinearRegression()
model2.fit(X_train,y_train)

LinearRegression()

In [148]:
model2.score(X_train,y_train)

0.09411944325600408

In [150]:
model2.score(X_test,y_test)

0.0476839889156101

In [1]:
# Information about minmaxscaler and standard scaler and more.: https://chat.openai.com/share/2226ca99-ad8f-4b46-8db8-4571b22cb57c

In [1]:
from sklearn.preprocessing import MinMaxScaler

In [2]:
sc=MinMaxScaler()     # ctrl+shift+spaceBar

In [3]:
import numpy as np
a=[1,2,3,4,5,6,7]
np.array(a)

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
b=np.array([[3],[1],[3],[4],[7],[2]])

In [8]:
print(b)

[[3]
 [1]
 [3]
 [4]
 [7]
 [2]]


In [10]:
sc.fit_transform(b)

array([[0.33333333],
       [0.        ],
       [0.33333333],
       [0.5       ],
       [1.        ],
       [0.16666667]])

In [11]:
b/7

array([[0.42857143],
       [0.14285714],
       [0.42857143],
       [0.57142857],
       [1.        ],
       [0.28571429]])

In [12]:
print(b)

[[3]
 [1]
 [3]
 [4]
 [7]
 [2]]


In [13]:
np.min(b)

1

In [14]:
np.max(b)

7

In [17]:
def MeraMinmaxScaler(arg):
    min_val=np.min(arg)
    max_val=np.max(arg)
    divisor=max_val-min_val
    return (b-min_val)/divisor

In [18]:
MeraMinmaxScaler(b)

array([[0.33333333],
       [0.        ],
       [0.33333333],
       [0.5       ],
       [1.        ],
       [0.16666667]])

In [19]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
sc=MinMaxScaler()

In [21]:
sc.fit_transform(b)

array([[0.33333333],
       [0.        ],
       [0.33333333],
       [0.5       ],
       [1.        ],
       [0.16666667]])

In [24]:
class MeraMinMaxScaler():

    def fit_transform1(self,arg):
        min_val=np.min(arg)
        max_val=np.max(arg)
        divisor=max_val-min_val
        return (b-min_val)/divisor

In [25]:
sc=MeraMinMaxScaler()

In [26]:
sc.fit_transform1(b)

array([[0.33333333],
       [0.        ],
       [0.33333333],
       [0.5       ],
       [1.        ],
       [0.16666667]])

In [27]:
b

array([[3],
       [1],
       [3],
       [4],
       [7],
       [2]])

In [28]:
b=np.array([[3,100],[1,222],[3,324],[4,213],[7,323],[2,323]])

In [29]:
b

array([[  3, 100],
       [  1, 222],
       [  3, 324],
       [  4, 213],
       [  7, 323],
       [  2, 323]])

In [30]:
from sklearn.preprocessing import MinMaxScaler

In [31]:
sc=MinMaxScaler()
sc.fit_transform(b)

array([[0.33333333, 0.        ],
       [0.        , 0.54464286],
       [0.33333333, 1.        ],
       [0.5       , 0.50446429],
       [1.        , 0.99553571],
       [0.16666667, 0.99553571]])