# MSE: stand for mean square error 

In [49]:
# importing important library 
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import seaborn as sn

In [7]:
# reading dataset using pandas "archive(2)/Salary Data.csv"

df=pd.read_csv("/home/new_krishna/Desktop/training /MachineLearningForProfessional/Machine_Learning/archive (2)/Salary Data.csv")

In [8]:
df

Age  Gender Education Level                      Job Title  \
0    32.0    Male      Bachelor's              Software Engineer   
1    28.0  Female        Master's                   Data Analyst   
2    45.0    Male             PhD                 Senior Manager   
3    36.0  Female      Bachelor's                Sales Associate   
4    52.0    Male        Master's                       Director   
..    ...     ...             ...                            ...   
370  35.0  Female      Bachelor's       Senior Marketing Analyst   
371  43.0    Male        Master's         Director of Operations   
372  29.0  Female      Bachelor's         Junior Project Manager   
373  34.0    Male      Bachelor's  Senior Operations Coordinator   
374  44.0  Female             PhD        Senior Business Analyst   

     Years of Experience    Salary  
0                    5.0   90000.0  
1                    3.0   65000.0  
2                   15.0  150000.0  
3                    7.0   60000.0  
4                   20.0  200000.0  
..                   ...       ...  
370                  8.0   85000.0  
371                 19.0  170000.0  
372                  2.0   40000.0  
373                  7.0   90000.0  
374                 15.0  150000.0  

[375 rows x 6 columns]

In [10]:
df1=df.iloc[:,-2:]

In [11]:
df1

Years of Experience    Salary
0                    5.0   90000.0
1                    3.0   65000.0
2                   15.0  150000.0
3                    7.0   60000.0
4                   20.0  200000.0
..                   ...       ...
370                  8.0   85000.0
371                 19.0  170000.0
372                  2.0   40000.0
373                  7.0   90000.0
374                 15.0  150000.0

[375 rows x 2 columns]

In [13]:
df1.isnull().sum()

Years of Experience    2
Salary                 2
dtype: int64

In [14]:
df1.dropna(inplace=True)

In [15]:
df1

Years of Experience    Salary
0                    5.0   90000.0
1                    3.0   65000.0
2                   15.0  150000.0
3                    7.0   60000.0
4                   20.0  200000.0
..                   ...       ...
370                  8.0   85000.0
371                 19.0  170000.0
372                  2.0   40000.0
373                  7.0   90000.0
374                 15.0  150000.0

[373 rows x 2 columns]

In [21]:
# slicing df1's years of experience into 2D array
X=df1.iloc[:,0:1].values     # this our feature

In [24]:
y=df1.Salary.values      # target 

In [26]:
y

array([ 90000.,  65000., 150000.,  60000., 200000.,  55000., 120000.,
        80000.,  45000., 110000.,  75000., 140000.,  65000., 130000.,
        40000., 125000.,  90000., 115000.,  35000., 180000.,  80000.,
       190000.,  50000.,  60000., 140000.,  45000., 110000.,  40000.,
       140000.,  90000., 250000.,  55000.,  75000.,  65000., 170000.,
        45000.,  60000., 115000.,  40000., 160000.,  80000., 190000.,
        60000.,  45000., 130000.,  40000.,  75000., 180000., 120000.,
        35000., 130000.,  85000.,  60000., 200000.,  50000.,  95000.,
        65000., 140000.,  55000., 105000., 170000.,  50000.,  80000.,
       180000.,  35000.,  90000., 120000.,  45000.,  90000., 150000.,
        65000.,  70000., 190000.,  40000., 120000.,  95000., 160000.,
       100000., 180000.,  55000.,  70000.,  80000.,  30000., 250000.,
        40000.,  95000.,  45000.,  80000., 135000.,  55000., 120000.,
        40000., 105000., 170000.,  75000.,  65000., 160000.,  35000.,
        90000., 1100

In [36]:
model=LinearRegression()
model.fit(X,y)

LinearRegression()

In [37]:
model.predict([[10]])

array([100366.32206189])

In [40]:
X

array([[ 5. ],
       [ 3. ],
       [15. ],
       [ 7. ],
       [20. ],
       [ 2. ],
       [12. ],
       [ 4. ],
       [ 1. ],
       [10. ],
       [ 3. ],
       [18. ],
       [ 6. ],
       [14. ],
       [ 2. ],
       [16. ],
       [ 7. ],
       [12. ],
       [ 0. ],
       [22. ],
       [ 5. ],
       [19. ],
       [ 2. ],
       [ 9. ],
       [13. ],
       [ 3. ],
       [11. ],
       [ 1. ],
       [15. ],
       [ 6. ],
       [25. ],
       [ 4. ],
       [ 3. ],
       [10. ],
       [20. ],
       [ 2. ],
       [ 7. ],
       [14. ],
       [ 1. ],
       [21. ],
       [ 5. ],
       [18. ],
       [ 3. ],
       [ 8. ],
       [13. ],
       [ 2. ],
       [ 5. ],
       [16. ],
       [11. ],
       [ 0. ],
       [22. ],
       [ 7. ],
       [12. ],
       [19. ],
       [ 3. ],
       [ 9. ],
       [ 2. ],
       [17. ],
       [ 4. ],
       [ 7. ],
       [23. ],
       [ 3. ],
       [12. ],
       [21. ],
       [ 1. ],
       [10. ],
       [19

In [39]:
y

array([ 90000.,  65000., 150000.,  60000., 200000.,  55000., 120000.,
        80000.,  45000., 110000.,  75000., 140000.,  65000., 130000.,
        40000., 125000.,  90000., 115000.,  35000., 180000.,  80000.,
       190000.,  50000.,  60000., 140000.,  45000., 110000.,  40000.,
       140000.,  90000., 250000.,  55000.,  75000.,  65000., 170000.,
        45000.,  60000., 115000.,  40000., 160000.,  80000., 190000.,
        60000.,  45000., 130000.,  40000.,  75000., 180000., 120000.,
        35000., 130000.,  85000.,  60000., 200000.,  50000.,  95000.,
        65000., 140000.,  55000., 105000., 170000.,  50000.,  80000.,
       180000.,  35000.,  90000., 120000.,  45000.,  90000., 150000.,
        65000.,  70000., 190000.,  40000., 120000.,  95000., 160000.,
       100000., 180000.,  55000.,  70000.,  80000.,  30000., 250000.,
        40000.,  95000.,  45000.,  80000., 135000.,  55000., 120000.,
        40000., 105000., 170000.,  75000.,  65000., 160000.,  35000.,
        90000., 1100

In [43]:
Y_pred_salary=model.predict(X)

In [44]:
Y_pred_salary

array([ 66143.76948947,  52454.7484605 , 134588.87463431,  79832.79051843,
       168811.42720673,  45610.23794601, 114055.34309085,  59299.25897498,
        38765.72743153, 100366.32206189,  52454.7484605 , 155122.40617776,
        72988.28000395, 127744.36411982,  45610.23794601, 141433.38514879,
        79832.79051843, 114055.34309085,  31921.21691704, 182500.4482357 ,
        66143.76948947, 161966.91669224,  45610.23794601,  93521.8115474 ,
       120899.85360534,  52454.7484605 , 107210.83257637,  38765.72743153,
       134588.87463431,  72988.28000395, 203033.97977915,  59299.25897498,
        52454.7484605 , 100366.32206189, 168811.42720673,  45610.23794601,
        79832.79051843, 127744.36411982,  38765.72743153, 175655.93772121,
        66143.76948947, 155122.40617776,  52454.7484605 ,  86677.30103292,
       120899.85360534,  45610.23794601,  66143.76948947, 141433.38514879,
       107210.83257637,  31921.21691704, 182500.4482357 ,  79832.79051843,
       114055.34309085, 1

In [45]:
# MSE: Mean Square error 

In [47]:
# calculate the error/Loss
Loss=y-Y_pred_salary

In [48]:
# Square of error
Loss*Loss

array([5.69119734e+08, 1.57383336e+08, 2.37502785e+08, 3.93339580e+08,
       9.72727073e+08, 8.81676314e+07, 3.53389458e+07, 4.28520679e+08,
       3.88661545e+07, 9.28077506e+07, 5.08288367e+08, 2.28687169e+08,
       6.38126174e+07, 5.08789322e+06, 3.14747698e+07, 2.70056147e+08,
       1.03372149e+08, 8.92376676e+05, 9.47890527e+06, 6.25224138e+06,
       1.91995124e+08, 7.85853760e+08, 1.92700109e+07, 1.12371185e+09,
       3.64815592e+08, 5.55732746e+07, 7.77945492e+06, 1.52342877e+06,
       2.92802777e+07, 2.89398617e+08, 2.20580706e+09, 1.84836277e+07,
       5.08288367e+08, 1.25077674e+09, 1.41270528e+06, 3.72390351e+05,
       3.93339580e+08, 1.62418817e+08, 1.52342877e+06, 2.45108386e+08,
       1.91995124e+08, 1.21644655e+09, 5.69308208e+07, 1.73699742e+09,
       8.28126644e+07, 3.14747698e+07, 7.84328189e+07, 1.48738378e+09,
       1.63562803e+08, 9.47890527e+06, 2.75629706e+09, 2.67000538e+07,
       2.92198012e+09, 1.44651543e+09, 6.02579000e+06, 2.18504110e+06,
      

In [52]:
Square_loss=np.square(Loss)
Square_loss

array([5.69119734e+08, 1.57383336e+08, 2.37502785e+08, 3.93339580e+08,
       9.72727073e+08, 8.81676314e+07, 3.53389458e+07, 4.28520679e+08,
       3.88661545e+07, 9.28077506e+07, 5.08288367e+08, 2.28687169e+08,
       6.38126174e+07, 5.08789322e+06, 3.14747698e+07, 2.70056147e+08,
       1.03372149e+08, 8.92376676e+05, 9.47890527e+06, 6.25224138e+06,
       1.91995124e+08, 7.85853760e+08, 1.92700109e+07, 1.12371185e+09,
       3.64815592e+08, 5.55732746e+07, 7.77945492e+06, 1.52342877e+06,
       2.92802777e+07, 2.89398617e+08, 2.20580706e+09, 1.84836277e+07,
       5.08288367e+08, 1.25077674e+09, 1.41270528e+06, 3.72390351e+05,
       3.93339580e+08, 1.62418817e+08, 1.52342877e+06, 2.45108386e+08,
       1.91995124e+08, 1.21644655e+09, 5.69308208e+07, 1.73699742e+09,
       8.28126644e+07, 3.14747698e+07, 7.84328189e+07, 1.48738378e+09,
       1.63562803e+08, 9.47890527e+06, 2.75629706e+09, 2.67000538e+07,
       2.92198012e+09, 1.44651543e+09, 6.02579000e+06, 2.18504110e+06,
      

In [75]:
np.mean(Square_loss)   # adding all the values/dividing values by number of terms

312090043.799001

In [54]:
sum(Square_loss)

array([5.69119734e+08, 1.57383336e+08, 2.37502785e+08, 3.93339580e+08,
       9.72727073e+08, 8.81676314e+07, 3.53389458e+07, 4.28520679e+08,
       3.88661545e+07, 9.28077506e+07, 5.08288367e+08, 2.28687169e+08,
       6.38126174e+07, 5.08789322e+06, 3.14747698e+07, 2.70056147e+08,
       1.03372149e+08, 8.92376676e+05, 9.47890527e+06, 6.25224138e+06,
       1.91995124e+08, 7.85853760e+08, 1.92700109e+07, 1.12371185e+09,
       3.64815592e+08, 5.55732746e+07, 7.77945492e+06, 1.52342877e+06,
       2.92802777e+07, 2.89398617e+08, 2.20580706e+09, 1.84836277e+07,
       5.08288367e+08, 1.25077674e+09, 1.41270528e+06, 3.72390351e+05,
       3.93339580e+08, 1.62418817e+08, 1.52342877e+06, 2.45108386e+08,
       1.91995124e+08, 1.21644655e+09, 5.69308208e+07, 1.73699742e+09,
       8.28126644e+07, 3.14747698e+07, 7.84328189e+07, 1.48738378e+09,
       1.63562803e+08, 9.47890527e+06, 2.75629706e+09, 2.67000538e+07,
       2.92198012e+09, 1.44651543e+09, 6.02579000e+06, 2.18504110e+06,
      

In [67]:
del sum

In [61]:
import builtins

In [70]:
sum([1])

1

In [74]:
sum(Square_loss)/Square_loss.shape[0]

312090043.7990014

In [73]:
Square_loss.shape[0]

373