In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
from sklearn.ensemble import AdaBoostClassifier

In [4]:
# loading our iris data 
df=pd.read_csv(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\classification_model\IRIS.csv")
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [9]:
# split data into feature and target

X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [18]:
#scale your data

from sklearn.preprocessing import MinMaxScaler 

In [20]:
sc=MinMaxScaler()
X_sc=sc.fit_transform(X)
X_sc

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [21]:
# split data into training and testing part 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_sc,y,train_size=0.7,random_state=42)

In [22]:
from sklearn.linear_model import LogisticRegression
base_model=LogisticRegression(max_iter=2000,multi_class='multinomial')
model=AdaBoostClassifier(estimator=base_model,n_estimators=100)
model.fit(X_train,y_train)

c:\Users\aimar\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoostClassifier(estimator=LogisticRegression(max_iter=2000,
                                                multi_class='multinomial'),
                   n_estimators=100)

In [25]:
sample=[[5.1,3.5,1.4,0.2]]
sample_sc=sc.transform(sample)
sample_sc

array([[0.22222222, 0.625     , 0.06779661, 0.04166667]])

In [26]:
model.predict(sample_sc)

array(['Iris-setosa'], dtype=object)

In [27]:
model.predict_proba(sample_sc)

array([[0.35297922, 0.33878613, 0.30823464]])

In [31]:
# split data into training and testing part 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_sc,y,train_size=0.7,random_state=42)
from sklearn.linear_model import LogisticRegression
base_model=LogisticRegression(max_iter=2000,multi_class='multinomial')
model=AdaBoostClassifier(estimator=base_model,n_estimators=100)
model.fit(X_train,y_train)
sample=[[5.1,3.5,1.4,0.2]]
sample_sc=sc.transform(sample)
print(sample_sc)
print(model.predict(sample_sc))
print(model.predict_proba(sample_sc))

c:\Users\aimar\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


[[0.22222222 0.625      0.06779661 0.04166667]]
['Iris-setosa']
[[0.35297922 0.33878613 0.30823464]]


In [39]:
# split data into training and testing part 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_sc,y,train_size=0.7,random_state=42)
# from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
base_model=RandomForestClassifier(max_depth=100000000000000000)
model=AdaBoostClassifier(estimator=base_model,n_estimators=100)
model.fit(X_train,y_train)
sample=[[5.1,3.5,1.4,0.2]]
sample_sc=sc.transform(sample)
print(sample_sc)
print(model.predict(sample_sc))
print(model.predict_proba(sample_sc))

[[0.22222222 0.625      0.06779661 0.04166667]]
['Iris-setosa']
[[1.00000000e+00 2.22044605e-16 2.22044605e-16]]


c:\Users\aimar\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
