In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
from sklearn.ensemble import RandomForestClassifier

In [2]:
df=pd.read_csv(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\classification_model\IRIS.csv")

In [3]:
X=df.iloc[:,:-1].values

In [4]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y=df.iloc[:,-1].values

In [6]:
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [7]:
#scaling my data using minmaxscaler
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
X_sc=sc.fit_transform(X)
X_sc

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_sc,y,train_size=0.70,random_state=42)

In [9]:
X_train.shape

(105, 4)

In [10]:
model=RandomForestClassifier(n_estimators=100)
model.fit(X_train,y_train)

RandomForestClassifier()

In [12]:
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [13]:
sample=[[5.1, 3.5, 1.4, 0.2]]

In [15]:
sample_sc=sc.transform(sample)
sample_sc

array([[0.22222222, 0.625     , 0.06779661, 0.04166667]])

In [16]:
model.predict(sample_sc)

array(['Iris-setosa'], dtype=object)

In [18]:
model.predict_proba(sample_sc)

array([[1., 0., 0.]])

In [20]:
df.species.value_counts()

species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [21]:
df.species.value_counts().index

Index(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='object', name='species')

In [28]:
X_train_pred=model.predict(X_train)

In [29]:
X_test_pred=model.predict(X_test)

In [30]:
from sklearn.metrics import accuracy_score

In [31]:
accuracy_score(X_train_pred,y_train)

1.0

In [32]:
accuracy_score(X_test_pred,y_test)

1.0

In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
from sklearn.ensemble import RandomForestClassifier
df=pd.read_csv(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\classification_model\IRIS.csv")
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values
#scaling my data using minmaxscaler
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
X_sc=sc.fit_transform(X)   # fit_transform scaling the data as well as finding min and max values of each column
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_sc,y,train_size=0.70,random_state=42)
model=RandomForestClassifier(n_estimators=100)
model.fit(X_train,y_train)
sample=[[5.1, 3.5, 1.4, 0.2]]
sample_sc=sc.transform(sample)     # tranform scale the data without calculating min and max values of each column. it is using fit_tranform scale to scale the data sample
print(sample_sc)
print("model prediction for a sample [[5.1, 3.5, 1.4, 0.2]]:",model.predict(sample_sc))
print("probability score:",model.predict_proba(sample_sc))
df.species.value_counts()
df.species.value_counts().index
X_train_pred=model.predict(X_train)
X_test_pred=model.predict(X_test)
from sklearn.metrics import accuracy_score
print("accruracy score for training sample:",accuracy_score(X_train_pred,y_train))
print("accuracy score of testing sample:",accuracy_score(X_test_pred,y_test))

[[0.22222222 0.625      0.06779661 0.04166667]]
model prediction for a sample [[5.1, 3.5, 1.4, 0.2]]: ['Iris-setosa']
probability score: [[1. 0. 0.]]
accruracy score for training sample: 1.0
accuracy score of testing sample: 1.0


In [40]:
sample=[[34,4323,324,435]]

In [41]:
sc.transform(sample)

array([[   8.25      , 1800.41666667,   54.74576271,  181.20833333]])

In [42]:
model.predict(sc.transform(sample))

array(['Iris-virginica'], dtype=object)

In [43]:
from sklearn.ensemble import RandomForestRegressor

In [44]:
df=pd.read_csv(r"C:\Users\aimar\OneDrive\Desktop\Youtube\MachineLearningForProfessional\archive (2)\Salary Data.csv")

In [45]:
df

Age  Gender Education Level                      Job Title  \
0    32.0    Male      Bachelor's              Software Engineer   
1    28.0  Female        Master's                   Data Analyst   
2    45.0    Male             PhD                 Senior Manager   
3    36.0  Female      Bachelor's                Sales Associate   
4    52.0    Male        Master's                       Director   
..    ...     ...             ...                            ...   
370  35.0  Female      Bachelor's       Senior Marketing Analyst   
371  43.0    Male        Master's         Director of Operations   
372  29.0  Female      Bachelor's         Junior Project Manager   
373  34.0    Male      Bachelor's  Senior Operations Coordinator   
374  44.0  Female             PhD        Senior Business Analyst   

     Years of Experience    Salary  
0                    5.0   90000.0  
1                    3.0   65000.0  
2                   15.0  150000.0  
3                    7.0   60000.0  
4                   20.0  200000.0  
..                   ...       ...  
370                  8.0   85000.0  
371                 19.0  170000.0  
372                  2.0   40000.0  
373                  7.0   90000.0  
374                 15.0  150000.0  

[375 rows x 6 columns]

In [47]:
df1=df.iloc[:,-2:]

In [48]:
df1

Years of Experience    Salary
0                    5.0   90000.0
1                    3.0   65000.0
2                   15.0  150000.0
3                    7.0   60000.0
4                   20.0  200000.0
..                   ...       ...
370                  8.0   85000.0
371                 19.0  170000.0
372                  2.0   40000.0
373                  7.0   90000.0
374                 15.0  150000.0

[375 rows x 2 columns]

In [56]:
df1.dropna(inplace=True)

In [57]:
X=df1.iloc[:,:-1].values

In [58]:
y=df1.iloc[:,-1].values

In [59]:
model_reg=RandomForestRegressor()

In [60]:
model_reg.fit(X,y)

RandomForestRegressor()

In [62]:
model_reg.predict([[25]])

array([201203.57142857])

In [63]:
model_reg.predict([[26]])

array([201203.57142857])

In [64]:
model_reg.predict([[100]])

array([201203.57142857])